# -------------------------
# Debug / Security
# -------------------------
debug.exception-trace = 0

kernel.kptr_restrict = 1
kernel.yama.ptrace_scope = 1
vm.mmap_min_addr = 32768

# fs.protected_hardlinks = 1
# fs.protected_symlinks = 1

kernel.sysrq = 176
kernel.nmi_watchdog = 0
kernel.printk = 4 4 1 7

# -------------------------
# Network Forwarding
# -------------------------
net.ipv4.ip_forward = 1
net.ipv6.conf.default.forwarding = 1

# -------------------------
# Reverse Path Filter
# -------------------------
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2

# -------------------------
# Route behavior
# -------------------------
net.ipv4.conf.default.ignore_routes_with_linkdown = 1
net.ipv6.conf.default.ignore_routes_with_linkdown = 1

# -------------------------
# Network Buffers (TCP/UDP)
# -------------------------
net.core.rmem_default = 262144
net.core.wmem_default = 262144

net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

net.core.netdev_max_backlog = 5000
net.core.somaxconn = 4096

# -------------------------
# UDP tuning
# -------------------------
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096

net.ipv4.udp_mem = 4096 87380 16777216

# -------------------------
# TCP tuning (optional but useful)
# -------------------------
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

net.ipv4.tcp_congestion_control = bbr

# -------------------------
# Security networking
# -------------------------
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.accept_redirects = 0

net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.send_redirects = 0
